server:
  port: 8085
  servlet:
    context-path: /api/notifications

spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME:adhikarilalit9968@gmail.com}
    password: ${GMAIL_APP_PASSWORD:osdi oyeg wtfk ntjw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:d9gv03v2pim8v25absv0.any.ap-south-1.mpx.prd.cloud.redpanda.com:9092}
    listener:
      auto-startup: ${ENABLE_KAFKA:true}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME:admin}" password="${KAFKA_PASSWORD:password}";'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: ${ENABLE_EUREKA:true}
    fetch-registry: ${ENABLE_EUREKA:true}
  instance:
    prefer-ip-address: true

notification:
  email:
    enabled: true
    from: ${GMAIL_USERNAME:adhikarilalit9968@gmail.com}
  sms:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
