package com.ticketing.genai.service;

import com.ticketing.genai.dto.ItineraryResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Slf4j
@Service
@RequiredArgsConstructor
public class ItineraryService {

    private final GenerationService generationService;

    public ItineraryResponse generateItinerary(String bookingId) {
        String defaultMarkdown = "# ✈ Your Travel Itinerary\n\n" +
                "## Booking Reference: " + bookingId + "\n\n" +
                "### Flight Details\n" +
                "- **Flight**: AI-101\n" +
                "- **Route**: Delhi (DEL) → Mumbai (BOM)\n" +
                "- **Date**: 2026-08-01\n" +
                "- **Departure**: 18:00 IST\n" +
                "- **Arrival**: 20:15 IST\n" +
                "- **Seat**: 12A (Economy)\n\n" +
                "### Pre-Flight Checklist\n" +
                "- [ ] Web check-in (opens 48 hours before departure)\n" +
                "- [ ] Download boarding pass\n" +
                "- [ ] Carry valid photo ID\n\n" +
                "### Airport Information\n" +
                "**Departure**: Terminal 3, Indira Gandhi International Airport\n" +
                "- Recommended arrival: 2 hours before departure\n\n" +
                "*Generated by AAI Ticketing AI Assistant*";

        String finalItinerary = defaultMarkdown;
        try {
            String prompt = String.format("""
                    You are AeroIndia's AI Travel Assistant. Create a formatted markdown travel itinerary guide for booking ID %s (Flight AI-101 DEL -> BOM).
                    Include flight times, pre-flight checklist, terminal tips, and travel suggestions in Mumbai. Keep it clean and formatted in markdown.
                    """, bookingId);

            String generated = generationService.generate(prompt);
            if (generated != null && !generated.isBlank()) {
                finalItinerary = generated.trim();
            }
        } catch (Exception e) {
            log.error("Failed to generate custom itinerary via Gemini: {}. Using default template.", e.getMessage());
        }

        return ItineraryResponse.builder()
                .bookingId(bookingId)
                .itinerary(finalItinerary)
                .generatedAt(LocalDateTime.now())
                .build();
    }
}
