package com.ticketing.genai.service;

import com.ticketing.genai.dto.ItineraryResponse;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class ItineraryService {

    public ItineraryResponse generateItinerary(String bookingId) {
        String markdown = "# ✈ Your Travel Itinerary\n\n" +
                "## Booking Reference: " + bookingId + "\n\n" +
                "### Flight Details\n" +
                "- **Flight**: AI-101\n" +
                "- **Route**: Delhi (DEL) → Mumbai (BOM)\n" +
                "- **Date**: 2026-08-01\n" +
                "- **Departure**: 18:00 IST\n" +
                "- **Arrival**: 20:15 IST\n" +
                "- **Seat**: 12A (Economy)\n\n" +
                "### Pre-Flight Checklist\n" +
                "- [ ] Web check-in (opens 48 hours before departure)\n" +
                "- [ ] Download boarding pass\n" +
                "- [ ] Carry valid photo ID\n\n" +
                "### Airport Information\n" +
                "**Departure**: Terminal 3, Indira Gandhi International Airport\n" +
                "- Recommended arrival: 2 hours before departure\n\n" +
                "*Generated by AAI Ticketing AI Assistant*";
                
        return ItineraryResponse.builder()
                .bookingId(bookingId)
                .itinerary(markdown)
                .generatedAt(LocalDateTime.now())
                .build();
    }
}
