server:
  port: 8084
  servlet:
    context-path: /api/payments

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:ticketing_payment;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: "${SPRING_DATASOURCE_PASSWORD:}"
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    register-with-eureka: ${ENABLE_EUREKA:false}
    fetch-registry: ${ENABLE_EUREKA:false}
  instance:
    prefer-ip-address: true

payment:
  gateway:
    success-rate: 90
    min-latency-ms: 200
    max-latency-ms: 800

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
