server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/api/flights/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /api/auth/v3/api-docs
      - name: Flight Service  
        url: /api/flights/v3/api-docs
      - name: Booking Service
        url: /api/bookings/v3/api-docs
      - name: Payment Service
        url: /api/payments/v3/api-docs
